name: MessingAround
version: '${project.version}'
main: com.hill.messing.messingaround.MessingAround
api-version: 1.19
commands:
  fwork:
    aliases: fw
  potion:
    aliases: p
  weather:
    aliases: w
  time:
    aliases: t
